export const NAVIGATION_BOTTOM_TAB = 'NAVIGATION_BOTTOM_TAB';
export const NAVIGATION_MAIN_APP = 'NAVIGATION_MAIN_APP';
export const NAVIGATION_TAB_HOME = 'NAVIGATION_TAB_HOME';
export const NAVIGATION_TAB_APPOINTMENT = 'NAVIGATION_TAB_APPOINTMENT';
export const NAVIGATION_TAB_VACXIN = 'NAVIGATION_TAB_VACXIN';
export const NAVIGATION_TAB_PROFILE = 'NAVIGATION_TAB_PROFILE';
export const NAVIGATION_TAB_PERSONAL = 'NAVIGATION_TAB_PERSONAL'

//
export const ROUTE_SPLASH = 'ROUTE_SPLASH';

//
export const ROUTE_LOGIN = 'ROUTE_LOGIN';

//
export const ROUTE_HOME = 'ROUTE_HOME';
export const ROUTE_EDIT_PASSWORD = 'ROUTE_EDIT_PASSWORD';

//
export const ROUTE_EXAMPLE1 = 'ROUTE_EXAMPLE1';
export const ROUTE_EXAMPLE2 = 'ROUTE_EXAMPLE2';
